In [9]:
from google.colab import files
import pandas as pd
uploaded = files.upload()
df = pd.read_csv("india_yearly_full_release_long_format.csv")
display(df.head())

Saving india_yearly_full_release_long_format.csv to india_yearly_full_release_long_format (3).csv

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
0,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Clean,MW,17.44,NaN,NaN
1,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Fossil,MW,40.05,NaN,NaN
2,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Gas and Other Fossil,MW,40.05,NaN,NaN
3,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,"Hydro, Bioenergy and Other Renewables",MW,5.25,NaN,NaN
4,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Renewables,MW,17.44,NaN,NaN

In [10]:
df = df[df['Subcategory'] != 'Aggregate fuel']
df = df.iloc[:, :-2]
display(df.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
6,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Bioenergy,MW,0.00
7,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Coal,MW,0.00
8,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Gas,MW,0.00
9,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Hydro,MW,5.25
10,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Nuclear,MW,0.00

In [11]:
df.to_csv('yearly_usage.csv', index=False)
from google.colab import files
files.download('yearly_usage.csv')

In [12]:
unique_categories = df['Category'].unique()
print(unique_categories)

['Capacity' 'Electricity generation' 'Power sector emissions']

In [13]:
df_capacity = df[df['Category'] == 'Capacity']
display(df_capacity.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
6,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Bioenergy,MW,0.00
7,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Coal,MW,0.00
8,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Gas,MW,0.00
9,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Hydro,MW,5.25
10,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Nuclear,MW,0.00

In [14]:
df_electricity_generation = df[df['Category'] == 'Electricity generation']
display(df_electricity_generation.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
27,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Bioenergy,%,0.00
28,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Coal,%,0.00
29,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Gas,%,0.00
30,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Hydro,%,6.84
31,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Nuclear,%,0.00

In [15]:
df_power_sector_emissions = df[df['Category'] == 'Power sector emissions']
display(df_power_sector_emissions.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
58,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,CO2 intensity,CO2 intensity,gCO2/kWh,569.91
59,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Bioenergy,%,0.00
60,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Coal,%,0.00
61,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Gas,%,0.00
62,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Hydro,%,0.18

In [16]:
df_capacity.to_csv('capacity_data.csv', index=False)
files.download('capacity_data.csv')

In [17]:
df_electricity_generation.to_csv('electricity_generation_data.csv', index=False)
files.download('electricity_generation_data.csv')

In [18]:
df_power_sector_emissions.to_csv('power_sector_emissions_data.csv', index=False)
files.download('power_sector_emissions_data.csv')

In [19]:
uploaded = files.upload()
df1 = pd.read_csv("india_monthly_full_release_long_format.csv")
display(df1.head())

Saving india_monthly_full_release_long_format.csv to india_monthly_full_release_long_format.csv

,Country,Country code,State,State code,State type,Date,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
0,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Clean,MW,NaN,NaN,NaN
1,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Fossil,MW,NaN,NaN,NaN
2,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Gas and Other Fossil,MW,NaN,NaN,NaN
3,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,"Hydro, Bioenergy and Other Renewables",MW,NaN,NaN,NaN
4,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Renewables,MW,NaN,NaN,NaN

In [20]:
df1 = df1[df1['Subcategory'] != 'Aggregate fuel']
df1 = df1.iloc[:, :-2]
display(df1.head())

,Country,Country code,State,State code,State type,Date,Category,Subcategory,Variable,Unit,Value
6,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Bioenergy,MW,NaN
7,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Coal,MW,NaN
8,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Gas,MW,NaN
9,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Hydro,MW,NaN
10,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Nuclear,MW,NaN

In [23]:
df1['Date'] = pd.to_datetime(df1['Date'])
df1['Year'] = df1['Date'].dt.year
df1['Month'] = df1['Date'].dt.month
df1 = df1.drop(columns=['Date'])

# Get current column names
cols = df1.columns.tolist()

# Remove 'Year' and 'Month' from their current positions
cols.remove('Year')
cols.remove('Month')

# Insert 'Year' and 'Month' at the beginning of the list
new_cols_order = ['Year', 'Month'] + cols

# Reindex the DataFrame with the new column order
df1 = df1[new_cols_order]
display(df1.head())

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
6,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Bioenergy,MW,NaN
7,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Coal,MW,NaN
8,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Gas,MW,NaN
9,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Hydro,MW,NaN
10,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Nuclear,MW,NaN

In [24]:
cat = df1['Category'].unique()
print(cat)
df1_capacity = df1[df1['Category'] == 'Capacity']
display(df1_capacity.head())

df1_electricity_generation = df1[df1['Category'] == 'Electricity generation']
display(df1_electricity_generation.head())

df1_power_sector_emissions = df1[df1['Category'] == 'Power sector emissions']
display(df1_power_sector_emissions.head())

['Capacity' 'Electricity generation' 'Power sector emissions']

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
6,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Bioenergy,MW,NaN
7,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Coal,MW,NaN
8,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Gas,MW,NaN
9,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Hydro,MW,NaN
10,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Nuclear,MW,NaN

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
27,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Bioenergy,%,0.00
28,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Coal,%,0.00
29,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Gas,%,0.00
30,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Hydro,%,11.86
31,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Nuclear,%,0.00

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
58,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,CO2 intensity,CO2 intensity,gCO2/kWh,521.19
59,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Bioenergy,%,0.00
60,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Coal,%,0.00
61,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Gas,%,0.00
62,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Hydro,%,0.03

In [26]:
df1_electricity_generation_monthly_state = df1_electricity_generation.groupby(['Year', 'Month', 'State'])['Value'].sum().reset_index()
display(df1_electricity_generation_monthly_state.head())

   Year  Month                State     Value
0  2019      1  Andaman and Nicobar    118.87
1  2019      1       Andhra Pradesh  10973.98
2  2019      1    Arunachal Pradesh    184.86
3  2019      1                Assam   1295.02
4  2019      1                Bihar   6382.87