In [1]:
from google.colab import files
import pandas as pd
uploaded = files.upload()
df = pd.read_csv("india_yearly_full_release_long_format.csv")
display(df.head())

Saving india_yearly_full_release_long_format.csv to india_yearly_full_release_long_format.csv

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
0,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Clean,MW,17.44,NaN,NaN
1,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Fossil,MW,40.05,NaN,NaN
2,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Gas and Other Fossil,MW,40.05,NaN,NaN
3,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,"Hydro, Bioenergy and Other Renewables",MW,5.25,NaN,NaN
4,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Aggregate fuel,Renewables,MW,17.44,NaN,NaN

In [2]:
df = df[df['Subcategory'] != 'Aggregate fuel']
df = df.iloc[:, :-2]
display(df.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
6,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Bioenergy,MW,0.00
7,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Coal,MW,0.00
8,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Gas,MW,0.00
9,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Hydro,MW,5.25
10,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Nuclear,MW,0.00

In [3]:
df.to_csv('yearly_usage.csv', index=False)
from google.colab import files
files.download('yearly_usage.csv')

In [4]:
unique_categories = df['Category'].unique()
print(unique_categories)

['Capacity' 'Electricity generation' 'Power sector emissions']

In [5]:
df_capacity = df[df['Category'] == 'Capacity']
display(df_capacity.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
6,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Bioenergy,MW,0.00
7,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Coal,MW,0.00
8,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Gas,MW,0.00
9,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Hydro,MW,5.25
10,India,IND,Andaman and Nicobar,AN,Union territory,2019,Capacity,Fuel,Nuclear,MW,0.00

In [6]:
df_electricity_generation = df[df['Category'] == 'Electricity generation']
display(df_electricity_generation.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
27,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Bioenergy,%,0.00
28,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Coal,%,0.00
29,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Gas,%,0.00
30,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Hydro,%,6.84
31,India,IND,Andaman and Nicobar,AN,Union territory,2019,Electricity generation,Fuel,Nuclear,%,0.00

In [7]:
df_power_sector_emissions = df[df['Category'] == 'Power sector emissions']
display(df_power_sector_emissions.head())

,Country,Country code,State,State code,State type,Year,Category,Subcategory,Variable,Unit,Value
58,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,CO2 intensity,CO2 intensity,gCO2/kWh,569.91
59,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Bioenergy,%,0.00
60,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Coal,%,0.00
61,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Gas,%,0.00
62,India,IND,Andaman and Nicobar,AN,Union territory,2019,Power sector emissions,Fuel,Hydro,%,0.18

In [8]:
df_capacity.to_csv('capacity_data.csv', index=False)
files.download('capacity_data.csv')

In [9]:
df_electricity_generation.to_csv('electricity_generation_data.csv', index=False)
files.download('electricity_generation_data.csv')

In [10]:
df_power_sector_emissions.to_csv('power_sector_emissions_data.csv', index=False)
files.download('power_sector_emissions_data.csv')

In [11]:
uploaded = files.upload()
df1 = pd.read_csv("india_monthly_full_release_long_format.csv")
display(df1.head())

Saving india_monthly_full_release_long_format.csv to india_monthly_full_release_long_format.csv

,Country,Country code,State,State code,State type,Date,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
0,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Clean,MW,NaN,NaN,NaN
1,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Fossil,MW,NaN,NaN,NaN
2,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Gas and Other Fossil,MW,NaN,NaN,NaN
3,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,"Hydro, Bioenergy and Other Renewables",MW,NaN,NaN,NaN
4,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Aggregate fuel,Renewables,MW,NaN,NaN,NaN

In [12]:
df1 = df1[df1['Subcategory'] != 'Aggregate fuel']
df1 = df1.iloc[:, :-2]
display(df1.head())

,Country,Country code,State,State code,State type,Date,Category,Subcategory,Variable,Unit,Value
6,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Bioenergy,MW,NaN
7,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Coal,MW,NaN
8,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Gas,MW,NaN
9,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Hydro,MW,NaN
10,India,IND,Andaman and Nicobar,AN,Union territory,2019-01-01,Capacity,Fuel,Nuclear,MW,NaN

In [13]:
df1['Date'] = pd.to_datetime(df1['Date'])
df1['Year'] = df1['Date'].dt.year
df1['Month'] = df1['Date'].dt.month
df1 = df1.drop(columns=['Date'])

# Get current column names
cols = df1.columns.tolist()

# Remove 'Year' and 'Month' from their current positions
cols.remove('Year')
cols.remove('Month')

# Insert 'Year' and 'Month' at the beginning of the list
new_cols_order = ['Year', 'Month'] + cols

# Reindex the DataFrame with the new column order
df1 = df1[new_cols_order]
display(df1.head())

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
6,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Bioenergy,MW,NaN
7,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Coal,MW,NaN
8,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Gas,MW,NaN
9,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Hydro,MW,NaN
10,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Nuclear,MW,NaN

In [14]:
cat = df1['Category'].unique()
print(cat)
df1_capacity = df1[df1['Category'] == 'Capacity']
display(df1_capacity.head())

df1_electricity_generation = df1[df1['Category'] == 'Electricity generation']
display(df1_electricity_generation.head())

df1_power_sector_emissions = df1[df1['Category'] == 'Power sector emissions']
display(df1_power_sector_emissions.head())

['Capacity' 'Electricity generation' 'Power sector emissions']

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
6,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Bioenergy,MW,NaN
7,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Coal,MW,NaN
8,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Gas,MW,NaN
9,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Hydro,MW,NaN
10,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Capacity,Fuel,Nuclear,MW,NaN

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
27,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Bioenergy,%,0.00
28,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Coal,%,0.00
29,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Gas,%,0.00
30,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Hydro,%,11.86
31,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Electricity generation,Fuel,Nuclear,%,0.00

,Year,Month,Country,Country code,State,State code,State type,Category,Subcategory,Variable,Unit,Value
58,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,CO2 intensity,CO2 intensity,gCO2/kWh,521.19
59,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Bioenergy,%,0.00
60,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Coal,%,0.00
61,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Gas,%,0.00
62,2019,1,India,IND,Andaman and Nicobar,AN,Union territory,Power sector emissions,Fuel,Hydro,%,0.03

In [15]:
df1_electricity_generation_monthly_state = df1_electricity_generation.groupby(['Year', 'Month', 'State'])['Value'].sum().reset_index()
display(df1_electricity_generation_monthly_state.head())

   Year  Month                State     Value
0  2019      1  Andaman and Nicobar    118.87
1  2019      1       Andhra Pradesh  10973.98
2  2019      1    Arunachal Pradesh    184.86
3  2019      1                Assam   1295.02
4  2019      1                Bihar   6382.87

In [18]:
df1_electricity_generation_yearly = df1_electricity_generation.groupby(['Year'])['Value'].mean().reset_index()
display(df1_electricity_generation_yearly.head())

   Year       Value
0  2019  674.464614
1  2020  650.061988
2  2021  701.763340
3  2022  762.189907
4  2023  832.644056

In [19]:
df1_electricity_generation_monthly_state.to_csv('electricity_gener_yearly.csv', index=False)
files.download('electricity_gener_yearly.csv')

In [21]:
uploaded = files.upload()
df2 = pd.read_excel("temperature.xlsx")
display(df2.head())

Saving temperature.xlsx to temperature (1).xlsx

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Winter Season,Pre-Monsoon Season,Monsoon Season,Post-Monsoon Season,Annual
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec,NaN
1,1901.0,17.4522,19.3071,24.1723,28.1556,30.3041,30.4736,28.1482,26.8874,26.8976,25.9666,21.7871,18.4904,18.3797,27.544,28.0708,22.0814,24.8142
2,1902.0,18.6933,20.4414,25.4255,28.2190,30.5624,29.9625,27.8494,27.5445,26.4375,24.8570,21.0980,18.0340,19.5674,28.069,27.9485,21.3415,24.9224
3,1903.0,17.9156,19.4795,23.3988,27.7007,29.8527,30.2014,28.3421,26.8319,26.7067,25.0338,20.7062,17.6026,18.6975,26.984,27.9724,21.1142,24.4404
4,1904.0,17.5911,19.6260,23.7609,28.4068,29.7381,29.1320,27.1008,26.8433,26.5367,25.0456,20.9079,18.2641,18.6542,27.302,27.4032,21.4059,24.4207

In [24]:
# Drop the initial descriptive row from df2 before any filtering
df2_cleaned = df2.iloc[1:].copy()

# Convert 'Year' column to numeric, coercing errors to NaN
df2_cleaned['Year'] = pd.to_numeric(df2_cleaned['Year'], errors='coerce')

# Filter for rows where 'Year' is not NaN and is within the desired range (2019-2024)
df2_filtered = df2_cleaned[df2_cleaned['Year'].notna() &
                         (df2_cleaned['Year'] >= 2019) &
                         (df2_cleaned['Year'] <= 2024)].copy()

# Convert 'Year' column to integer type
df2_filtered['Year'] = df2_filtered['Year'].astype(int)

# Define the monthly temperature columns
month_cols = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

# Melt the DataFrame to transform monthly columns into rows
temp_melted = df2_filtered.melt(id_vars=['Year'], value_vars=month_cols, var_name='Month_Name', value_name='Temperature')

# Map month names to numerical month values
month_name_to_num = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
temp_melted['Month'] = temp_melted['Month_Name'].map(month_name_to_num)

# Select relevant columns for merging
temp_final = temp_melted[['Year', 'Month', 'Temperature']].copy()

# Merge df1_electricity_generation_monthly_state with temp_final
df_merged = pd.merge(df1_electricity_generation_monthly_state,
                     temp_final,
                     on=['Year', 'Month'],
                     how='left')

# Display the first few rows of the merged DataFrame
display(df_merged.head())

   Year  Month                State     Value  Temperature
0  2019      1  Andaman and Nicobar    118.87      17.9152
1  2019      1       Andhra Pradesh  10973.98      17.9152
2  2019      1    Arunachal Pradesh    184.86      17.9152
3  2019      1                Assam   1295.02      17.9152
4  2019      1                Bihar   6382.87      17.9152

In [25]:
df_merged.to_csv('merged_electricity_temperature_data.csv', index=False)
from google.colab import files
files.download('merged_electricity_temperature_data.csv')

In [27]:
uploaded = files.upload()
df3 = pd.read_excel("gdp.xls")
display(df3.head())

Saving gdp.xls to gdp (1).xls

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-02-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1.960000e+03,1.961000e+03,1.962000e+03,1.963000e+03,1.964000e+03,1.965000e+03,...,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2.023000e+03,2.024000e+03,2025.0
3,Aruba,ABW,GDP (constant 2015 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.999479e+09,3.104264e+09,3.203987e+09,3.243240e+09,2.468171e+09,2.831747e+09,3.132944e+09,3.374394e+09,3.604216e+09,NaN
4,Africa Eastern and Southern,AFE,GDP (constant 2015 US$),NY.GDP.MKTP.KD,1.543153e+11,1.549618e+11,1.672612e+11,1.766675e+11,1.848812e+11,1.943807e+11,...,9.293861e+11,9.542707e+11,9.800856e+11,9.999820e+11,9.718068e+11,1.016304e+12,1.054138e+12,1.074495e+12,1.104192e+12,NaN

In [28]:
# Load df3 again, specifying header=2 to correctly interpret column names
df3_gdp = pd.read_excel("gdp.xls", header=3)

# Filter for India and the specific indicator 'GDP (constant 2015 US$)'
india_gdp = df3_gdp[ (df3_gdp['Country Name'] == 'India') &
                     (df3_gdp['Indicator Name'] == 'GDP (constant 2015 US$)')
                   ].copy()

# Select only the relevant year columns and 'Country Name'
years = [str(year) for year in range(2019, 2025)]
india_gdp = india_gdp[['Country Name'] + years]

# Melt the DataFrame to transform year columns into rows
india_gdp_melted = india_gdp.melt(id_vars=['Country Name'],
                                 var_name='Year',
                                 value_name='GDP')

# Convert 'Year' to integer and 'GDP' to numeric
india_gdp_melted['Year'] = pd.to_numeric(india_gdp_melted['Year'], errors='coerce').astype(int)
india_gdp_melted['GDP'] = pd.to_numeric(india_gdp_melted['GDP'], errors='coerce')

# Select relevant columns for merging
gdp_final = india_gdp_melted[['Year', 'GDP']].copy()

# Merge df_merged with gdp_final on 'Year'
df_merged_with_gdp = pd.merge(df_merged,
                              gdp_final,
                              on='Year',
                              how='left')

# Display the first few rows of the updated merged DataFrame
display(df_merged_with_gdp.head())

   Year  Month                State     Value  Temperature           GDP
0  2019      1  Andaman and Nicobar    118.87      17.9152  2.689205e+12
1  2019      1       Andhra Pradesh  10973.98      17.9152  2.689205e+12
2  2019      1    Arunachal Pradesh    184.86      17.9152  2.689205e+12
3  2019      1                Assam   1295.02      17.9152  2.689205e+12
4  2019      1                Bihar   6382.87      17.9152  2.689205e+12

In [29]:
df_merged_with_gdp.to_csv('final_merged.csv', index=False)
from google.colab import files
files.download('final_merged.csv')